name: Ahsour 
on: push
jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
             - name: Checkout code
               run: echo "Hello World"
